### ISSUE TITLE
This looks really interesting to me

### ISSUE THREAD

**Issue by groodt** [springnz/sparkplug#39]
This project looks really interesting to me. I have been struggling to keep my Spark applications within a sensible level of complexity, and this would help greatly. I've got a few questions if anybody is so kind?

Are you still active on it or has it met your needs for the moment?
Would this work with the typed DataSets in Spark as well?
If you are no longer using this project, is there another project that follows similar functional programming principles?

**Comment by szoio** [comment]
Sorry this project is not really under active development at the moment.
As it turned out the priorities shifted for the team and the underlying business.
At about the same time, Spark 2.0 came out, which would have been quite a bit of work to move onto. The Spark project has moved on quite quickly, and we haven't had time to keep up.

I still think the premises of this project are still valid - especially handling the job submission process, as Spark itself still seems quite clunky at doing this. So as far as I'm concerned the need for something of the like still exists. I haven't surveyed the ecosystem lately to see what else is out there.

I enjoyed the work on Spark, and hopefully get the time to pick this up in the future.

In the functional programming world Frameless (https://github.com/typelevel/frameless) looks like a really nice project, but it is obviously addresses an unrelated use case.

**Comment by groodt** [comment]
Thanks for the response, totally understandable.

I'll see if I can use some of the ideas from Sparkplug or Frameless in any of my Spark based projects.
